---
# Variables here are applicable to all host groups
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
fetch_tmp_dir: "{{ playbook_dir }}/fetch_tmp"
fetch_log_dir: "{{ playbook_dir }}/fetch_log"
script_dir:    "{{ playbook_dir }}/scripts"
binary_dir:    "{{ playbook_dir }}/resources/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5
